config/routes.rb
Rails.application.routes.draw do
  get("/", { :controller => "quizzes", :action => "index" })

  # Routes for the Quiz resource:
   # CREATE
   post("/insert_quiz", { :controller => "quizzes", :action => "create" })
  
   # READ
   get("/quizzes", { :controller => "quizzes", :action => "index" })
   get("/quizzes/:path_id", { :controller => "quizzes", :action => "show" })
   
   # UPDATE
   post("/modify_quiz/:path_id", { :controller => "quizzes", :action => "update" })
   
   # DELETE
   get("/delete_quiz/:path_id", { :controller => "quizzes", :action => "destroy" })
 
  # CREATE
  post("/insert_quiz", { :controller => "quizzes", :action => "create" })
          
  # READ
  get("/quizzes", { :controller => "quizzes", :action => "index" })
  
  get("/quizzes/:path_id", { :controller => "quizzes", :action => "show" })
  
  # UPDATE
  
  post("/modify_quiz/:path_id", { :controller => "quizzes", :action => "update" })
  
  # DELETE
  get("/delete_quiz/:path_id", { :controller => "quizzes", :action => "destroy" })

  #------------------------------

  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:

  # get "/your_first_screen" => "pages#first"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :bigint           not null, primary key
#  content    :string
#  role       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quiz_id    :bigint           not null
#
# Indexes
#
#  index_messages_on_quiz_id  (quiz_id)
#
# Foreign Keys
#
#  fk_rails_...  (quiz_id => quizzes.id)
#
class Message < ApplicationRecord
  belongs_to :quiz
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint           not null, primary key
#  content    :string
#  difficulty :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quiz_id    :bigint           not null
#
# Indexes
#
#  index_questions_on_quiz_id  (quiz_id)
#
# Foreign Keys
#
#  fk_rails_...  (quiz_id => quizzes.id)
#
class Question < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
# == Schema Information
#
# Table name: quizzes
#
#  id         :bigint           not null, primary key
#  topic      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Quiz < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @quiz = Quiz.find(params[:quiz_id])
    user_message = @quiz.messages.create(content: params[:content], role: "user")

    # Call GPT-4
    gpt_response = GPTClient.ask(user_message.content, @quiz.topic)
    @quiz.messages.create(content: gpt_response, role: "system")

    redirect_to @quiz
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    matching_quizzes = Quiz.all

    @list_of_quizzes = matching_quizzes.order({ :created_at => :desc })

    render({ :template => "quizzes/index" })
  end

  def show
    the_id = params.fetch("path_id")
  
    matching_quizzes = Quiz.where({ id: the_id })
  
    @the_quiz = matching_quizzes.at(0)
  
    render({ template: "quizzes/show" })
  end

  def create
    the_quiz = Quiz.new
    the_quiz.topic = params.fetch("query_topic")

    if the_quiz.valid?
      the_quiz.save

      # Create system message

      system_message = Message.new
      system_message.quiz_id = the_quiz.id
      system_message.role = "system"
      system_message.body = "You are a #{the_quiz.topic} tutor. Ask the user five questions to assess their #{the_quiz.topic} proficiency. Start with an easy question. After each answer, increase or decrease the difficulty of the next question based on how well the user answered.

In the end, provide a score between 0 and 10."
      system_message.save

      # Create first user message

      user_message = Message.new
      user_message.role = "user"
      user_message.quiz_id = the_quiz.id
      user_message.body = "Can you assess my #{the_quiz.topic} proficiency?"
      user_message.save

      # Call API to get first assistant message

      client = OpenAI::Client.new(access_token: ENV.fetch("OPENAI_API_KEY"))

      message_list = [
        {
          "role" => "system",
          "content" => "You are a #{the_quiz.topic} tutor. Ask the user five questions to assess their #{the_quiz.topic} proficiency. Start with an easy question. After each answer, increase or decrease the difficulty of the next question based on how well the user answered.

In the end, provide a score between 0 and 10."
        },
        {
          "role" => "user",
          "content" => "Can you assess my #{the_quiz.topic} proficiency?"
        }
      ]

      api_response = client.chat(
        parameters: {
          model: ENV.fetch("OPENAI_MODEL"),
          messages: message_list
        }
      )

      assistant_content = api_response.fetch("choices").at(0).fetch("message").fetch("content")

      assistant_message = Message.new
      assistant_message.role = "assistant"
      assistant_message.quiz_id = the_quiz.id
      assistant_message.body = assistant_content
      assistant_message.save

      redirect_to("/quizzes/#{the_quiz.id}", { :notice => "Quiz created successfully." })
    else
      redirect_to("/quizzes/#{the_quiz.id}", { :alert => the_quiz.errors.full_messages.to_sentence })
    end
  end

  def update
    the_id = params.fetch("path_id")
    the_quiz = Quiz.where({ :id => the_id }).at(0)

    the_quiz.topic = params.fetch("query_topic")

    if the_quiz.valid?
      the_quiz.save
      redirect_to("/quizzes/#{the_quiz.id}", { :notice => "Quiz updated successfully."} )
    else
      redirect_to("/quizzes/#{the_quiz.id}", { :alert => the_quiz.errors.full_messages.to_sentence })
    end
  end

  def destroy
    the_id = params.fetch("path_id")
    the_quiz = Quiz.where({ :id => the_id }).at(0)

    the_quiz.destroy

    redirect_to("/quizzes", { :notice => "Quiz deleted successfully."} )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/index.html.erb
<div>
  <div>
    <h1>
      List of all quizzes
    </h1>
  </div>
</div>
<hr>
<div>
  <div>
    <h2>
      Add a new quiz
    </h2>
    <form action="/insert_quiz" method="post">
      <div>
        <label for="topic_box">
          Topic
        </label>
        <input type="text" id="topic_box" name="query_topic">
      </div>
      <button>
        Create quiz
      </button>
    </form>
  </div>
</div>
<hr>
<div>
  <div>
    <table border="1">
      <tr>
        <th>
          ID
        </th>
        <th>
          Topic
        </th>
        <th>
          Created at
        </th>
        <th>
          Updated at
        </th>
        <th>
        </th>
      </tr>
      <% @list_of_quizzes.each do |a_quiz| %>
      <tr>
        <td>
          <%= a_quiz.id %>
        </td>
        <td>
          <%= a_quiz.topic %>
        </td>
        <td>
          <%= time_ago_in_words(a_quiz.created_at) %> ago
        </td>
        <td>
          <%= time_ago_in_words(a_quiz.updated_at) %> ago
        </td>
        <td>
          <a href="<%= quiz_path(quiz) %>">Show details</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>
<hr>

app/views/quizzes/show.html.erb
<div>
  <div>
    <h1>
      Quiz #<%= @the_quiz.id %> details
    </h1>
    <div>
      <div>
        <a href="/quizzes">
          Go back
        </a>
      </div>
      <div>
        <a href="/delete_quiz/<%= @the_quiz.id %>">
          Delete quiz
        </a>
      </div>
    </div>
    <dl>
      <dt>
        Topic
      </dt>
      <dd>
        <%= @the_quiz.topic %>
      </dd>
      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_quiz.created_at) %> ago
      </dd>
      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@the_quiz.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>
<hr>
<div>
  <div>
    <h2>
      Edit quiz
    </h2>
    <form action="/modify_quiz/<%= @the_quiz.id %>"  method="post" >
      <div>
        <label for="topic_box">
          Topic
        </label>
        <input type="text" id="topic_box" name="query_topic" value="<%= @the_quiz.topic %>">
      </div>
      <button>
        Update quiz
      </button>
    </form>
  </div>
</div>
<hr>